[package]
name = "cracking-with-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"

[[include]]
path = "src/ex_02"

[[include]]
path = "src/ex_03"

[[include]]
path = "src/data_structures"
