[package]
name = "cracking-with-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"

[[include]]
path = "src/string"

[[include]]
path = "src/linked_list"

[[include]]
path = "src/search"

[[include]]
path = "src/sort"

[[include]]
path = "src/data_structures"
